node_front:
  ros__parameters:
    trig: 18
    echo: 19
    topic: /sensor/us_front
    target_distance: 8

node_sidefront:
  ros__parameters:
    trig: 16
    echo: 17
    topic: /sensor/us_sidefront
    target_distance: 8

node_siderear:
  ros__parameters:
    trig: 14
    echo: 15
    topic: /sensor/siderear
    target_distance: 8
