version: '3'

services:
  
  rpi_ros2_node:

    platform: linux/arm64

    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - FROM_IMAGE=ros:${ROS_DISTRO_NAME}-ros-core
        - USER=${USER_NAME}
        - ROS_DISTRO=${ROS_DISTRO_NAME}

    image: tedlinlab/ros2:${ARCH}-${ROS_DISTRO_NAME}-devel

    volumes:
      - ../ros_ws/src:/home/${USER_NAME}/ros_ws/src
      - ../dds/fastdds.xml:/fastdds.xml

    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
      - ROS_DOMAIN_ID=0
      - ROS_DISCOVERY_SERVER=${SERVER_IP}:11811

    env_file:
      - .env
    
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

    init: true # enable tini

    network_mode: host

    pid: host