# version: '3'
# version from 1.27.0 is optional
services:

  rtsp_server:

    image: bluenviron/mediamtx:latest-ffmpeg

    container_name: rtsp_server

    volumes:
      - ../rtsp/mediamtx.yaml:/mediamtx.yaml

    devices:
      - /dev/video0:/dev/video0

    env_file:
      - .env

    init: true

    network_mode: host

  dicovery_server_0:

    image: tedlinlab/ros2:${ARCH}-${ROS_DISTRO_NAME}-prod

    container_name: ros2_discovery_server_0

    command: fastdds discovery --server-id 0 -l 127.0.0.1 -p 11811

    init: true # enable tini

    env_file:
      - .env

    network_mode: host

    pid: host


  dicovery_server_1:

    image: tedlinlab/ros2:${ARCH}-${ROS_DISTRO_NAME}-prod

    container_name: ros2_discovery_server_1

    command: fastdds discovery --server-id 1 -l 127.0.0.1 -p 11888

    init: true # enable tini

    env_file:
      - .env

    network_mode: host

    pid: host


  wheel_control:

    extends:

      file: common-services.yaml

      service: rpi_ros2_node

    container_name: wheel_control

    command: ros2 run wheel_control wheel_control_node --ros-args -p reliability:=best_effort

    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811;127.0.0.1:11888
    
    depends_on:
      - dicovery_server_1
      - ultrasound_sensor
      - imu_sensor


  fan_control:

    extends:

      file: common-services.yaml

      service: rpi_ros2_node

    container_name: fan_control

    command: ros2 run fan_control fan_control_node --ros-args -p reliability:=best_effort

    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811;127.0.0.1:11888
    
    depends_on:
      - dicovery_server_1
      - ultrasound_sensor


  ultrasound_sensor:

    extends:

      file: common-services.yaml

      service: rpi_ros2_node

    container_name: ultrasound_sensor

    command: ros2 launch bringup ultrasound_launch.py

    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811

    depends_on:
      - dicovery_server_0
      

  imu_sensor:

    extends:

      file: common-services.yaml

      service: rpi_ros2_node

    container_name: imu_sensor

    command: ros2 run imu_sensor imu_sensor_node --ros-args -p reliability:=best_effort

    environment:
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
    
    depends_on:
      - dicovery_server_0
